#include "app/BattleObjectModuleAccessor.h"
#define AR(a) (*reinterpret_cast<void**>(reinterpret_cast<u8*>(a) + 0x98))
#define VT(m) (*reinterpret_cast<void***>(m))
namespace app::lua_bind {
// Pure dispatchers only (skipping add_motion_partial which has 11 instructions)
void* ArticleModule__generate_article_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2,u64 p3) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); return reinterpret_cast<void*(*)(void*,u64,bool,u64)>(VT(m)[0x78/8])(m,p1,p2,p3); }
void* ArticleModule__generate_article_enable_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2,u64 p3) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); return reinterpret_cast<void*(*)(void*,u64,bool,u64)>(VT(m)[0x80/8])(m,p1,p2,p3); }
void* ArticleModule__generate_article_have_item_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,u64 p3) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); return reinterpret_cast<void*(*)(void*,u64,u64,u64)>(VT(m)[0x88/8])(m,p1,p2,p3); }
void* ArticleModule__have_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,u64 p3,u64 p4,bool p5) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); return reinterpret_cast<void*(*)(void*,u64,u64,u64,u64,bool)>(VT(m)[0x90/8])(m,p1,p2,p3,p4,p5); }
void* ArticleModule__motion_kind_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); return reinterpret_cast<void*(*)(void*,u64,u64)>(VT(m)[0xb0/8])(m,p1,p2); }
void ArticleModule__change_motion_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,bool p3) { auto* m=AR(a); reinterpret_cast<void(*)(void*,u64,u64,bool)>(VT(m)[0xb8/8])(m,p1,p2,p3); }
void ArticleModule__change_motion_from_no_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,u64 p3,bool p4) { auto* m=AR(a); reinterpret_cast<void(*)(void*,u64,u64,u64,bool)>(VT(m)[0xc0/8])(m,p1,p2,p3,p4); }
void ArticleModule__add_motion_2nd_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,bool p3) { auto* m=AR(a); reinterpret_cast<void(*)(void*,u64,u64,bool)>(VT(m)[0xc8/8])(m,p1,p2,p3); }
void* ArticleModule__motion_kind_2nd_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); return reinterpret_cast<void*(*)(void*,u64,u64)>(VT(m)[0xd0/8])(m,p1,p2); }
void* ArticleModule__change_status_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,u64 p3) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); return reinterpret_cast<void*(*)(void*,u64,u64,u64)>(VT(m)[0x108/8])(m,p1,p2,p3); }
void* ArticleModule__change_status_exist_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); return reinterpret_cast<void*(*)(void*,u64,u64)>(VT(m)[0x110/8])(m,p1,p2); }
void ArticleModule__set_default_visibility_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,u64 p3) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); reinterpret_cast<void(*)(void*,u64,u64,u64)>(VT(m)[0x130/8])(m,p1,p2,p3); }
void ArticleModule__set_flag_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2,u64 p3) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); reinterpret_cast<void(*)(void*,u64,bool,u64)>(VT(m)[0x148/8])(m,p1,p2,p3); }
bool ArticleModule__is_flag_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); return reinterpret_cast<bool(*)(void*,u64,u64)>(VT(m)[0x150/8])(m,p1,p2); }
bool ArticleModule__is_flag_from_no_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,u64 p3) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); return reinterpret_cast<bool(*)(void*,u64,u64,u64)>(VT(m)[0x158/8])(m,p1,p2,p3); }
void* ArticleModule__get_int_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); return reinterpret_cast<void*(*)(void*,u64,u64)>(VT(m)[0x168/8])(m,p1,p2); }
void ArticleModule__set_float_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); reinterpret_cast<void(*)(void*,u64,u64)>(VT(m)[0x180/8])(m,p1,p2); }
void* ArticleModule__get_float_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); return reinterpret_cast<void*(*)(void*,u64,u64)>(VT(m)[0x188/8])(m,p1,p2); }
void* ArticleModule__remove_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); return reinterpret_cast<void*(*)(void*,u64,u64)>(VT(m)[0x1b0/8])(m,p1,p2); }
void* ArticleModule__remove_exist_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); return reinterpret_cast<void*(*)(void*,u64,u64)>(VT(m)[0x1b8/8])(m,p1,p2); }
void ArticleModule__remove_exist_object_id_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AR(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x1c0/8])(m,p1); }
bool ArticleModule__is_exist_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AR(a); return reinterpret_cast<bool(*)(void*,u64)>(VT(m)[0x1c8/8])(m,p1); }
u32 ArticleModule__get_num_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AR(a); return reinterpret_cast<u32(*)(void*,u64)>(VT(m)[0x1d0/8])(m,p1); }
bool ArticleModule__is_generatable_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AR(a); return reinterpret_cast<bool(*)(void*,u64)>(VT(m)[0x1d8/8])(m,p1); }
u32 ArticleModule__get_active_num_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AR(a); return reinterpret_cast<u32(*)(void*,u64)>(VT(m)[0x1e0/8])(m,p1); }
void* ArticleModule__get_article_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AR(a); return reinterpret_cast<void*(*)(void*,u64)>(VT(m)[0x208/8])(m,p1); }
u32 ArticleModule__get_article_from_no_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); return reinterpret_cast<u32(*)(void*,u64,u64)>(VT(m)[0x210/8])(m,p1,p2); }
void* ArticleModule__get_joint_pos_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,u64 p3) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); return reinterpret_cast<void*(*)(void*,u64,u64,u64)>(VT(m)[0x258/8])(m,p1,p2,p3); }
void* ArticleModule__get_joint_rotate_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,u64 p3) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); return reinterpret_cast<void*(*)(void*,u64,u64,u64)>(VT(m)[0x260/8])(m,p1,p2,p3); }
// Additional ArticleModule dispatchers
void ArticleModule__shoot_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,bool p3) { auto* m=AR(a); reinterpret_cast<void(*)(void*,u64,u64,bool)>(VT(m)[0x98/8])(m,p1,p2,p3); }
void ArticleModule__shoot_exist_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,bool p3) { auto* m=AR(a); reinterpret_cast<void(*)(void*,u64,u64,bool)>(VT(m)[0xa0/8])(m,p1,p2,p3); }
void ArticleModule__set_pos_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AR(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0xa8/8])(m,p1); }
void ArticleModule__set_weight_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2) { auto* m=AR(a); reinterpret_cast<void(*)(void*,u64,bool)>(VT(m)[0xd8/8])(m,p1,p2); }
void ArticleModule__set_frame_2nd_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); reinterpret_cast<void(*)(void*,u64,bool)>(VT(m)[0xf8/8])(m,p1,p2); }
void ArticleModule__set_rate_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x100/8])(m,p1); }
void ArticleModule__set_visibility_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,u64 p3,u64 p4) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); reinterpret_cast<void(*)(void*,u64,u64,u64,u64)>(VT(m)[0x128/8])(m,p1,p2,p3,p4); }
void ArticleModule__set_visibility_whole_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2,u64 p3) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); reinterpret_cast<void(*)(void*,u64,bool,u64)>(VT(m)[0x118/8])(m,p1,p2,p3); }
void ArticleModule__set_visibility_whole_2_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,u64 p3,u64 p4) { auto* m=AR(a); reinterpret_cast<void(*)(void*,u64,u64,u64,u64)>(VT(m)[0x128/8])(m,p1,p2,p3,p4); }
void ArticleModule__set_int_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,u64 p3) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); reinterpret_cast<void(*)(void*,u64,u64,u64)>(VT(m)[0x160/8])(m,p1,p2,p3); }
void ArticleModule__set_int_from_no_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,u64 p3) { auto* m=AR(a); reinterpret_cast<void(*)(void*,u64,u64,u64)>(VT(m)[0x160/8])(m,p1,p2,p3); }
void ArticleModule__set_float_from_no_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,u64 p3) { auto* m=AR(a); reinterpret_cast<void(*)(void*,u64,u64,u64)>(VT(m)[0x170/8])(m,p1,p2,p3); }
void ArticleModule__get_float_from_no_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2) { auto* m=AR(a); reinterpret_cast<void(*)(void*,u64,u64)>(VT(m)[0x190/8])(m,p1,p2); }
void* ArticleModule__get_joint_scale_impl(BattleObjectModuleAccessor* a) { auto* m=AR(a); return reinterpret_cast<void*(*)(void*)>(VT(m)[0x278/8])(m); }
void ArticleModule__set_frame_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0xf0/8])(m,p1); }
void ArticleModule__set_situation_kind_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2) { auto* m=reinterpret_cast<void*>(*reinterpret_cast<u64*>(reinterpret_cast<u8*>(a)+0x98)); reinterpret_cast<void(*)(void*,u64,u64)>(VT(m)[0x140/8])(m,p1,p2); }
} // namespace app::lua_bind
