#include "app/BattleObjectModuleAccessor.h"
#define AT(a) (*reinterpret_cast<void**>(reinterpret_cast<u8*>(a) + 0xA0))
#define VT(m) (*reinterpret_cast<void***>(m))
namespace app::lua_bind {
// Existing
bool AttackModule__is_attack_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2) { auto* m=AT(a); return reinterpret_cast<bool(*)(void*,u64,bool)>(VT(m)[0xC8/8])(m,p1,p2); }
bool AttackModule__is_invalid_invincible_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2) { auto* m=AT(a); return reinterpret_cast<bool(*)(void*,u64,bool)>(VT(m)[0xD8/8])(m,p1,p2); }
bool AttackModule__is_invalid_xlu_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2) { auto* m=AT(a); return reinterpret_cast<bool(*)(void*,u64,bool)>(VT(m)[0xE8/8])(m,p1,p2); }
bool AttackModule__is_hit_abs_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); return reinterpret_cast<bool(*)(void*,u64)>(VT(m)[0xF0/8])(m,p1); }
bool AttackModule__is_infliction_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); return reinterpret_cast<bool(*)(void*,u64)>(VT(m)[0x3C0/8])(m,p1); }
bool AttackModule__is_infliction_status_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); return reinterpret_cast<bool(*)(void*,u64)>(VT(m)[0x3D0/8])(m,p1); }
bool AttackModule__is_power_up_reaction_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x5A0/8])(m); }
bool AttackModule__is_attack_occur_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); return reinterpret_cast<bool(*)(void*,u64)>(VT(m)[0x5C8/8])(m,p1); }
bool AttackModule__is_constraint_pos_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); return reinterpret_cast<bool(*)(void*,u64)>(VT(m)[0x5D8/8])(m,p1); }
bool AttackModule__is_no_dead_damage_fly_effect_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x5E8/8])(m); }
bool AttackModule__is_critical_attack_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x6D8/8])(m); }
void AttackModule__set_is_critical_attack_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x6F0/8])(m,p1); }
// Batch 1 — 59 new dispatchers
void AttackModule__clear_all_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); reinterpret_cast<void(*)(void*)>(VT(m)[0x50/8])(m); }
void AttackModule__clear_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64,bool)>(VT(m)[0x58/8])(m,p1,p2); }
void AttackModule__sleep_partialy_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64,bool)>(VT(m)[0x60/8])(m,p1,p2); }
void AttackModule__set_attack_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x68/8])(m,p1); }
void AttackModule__set_attack_2_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x70/8])(m,p1); }
void AttackModule__set_absolute_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x78/8])(m,p1); }
void AttackModule__hit_absolute_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x80/8])(m,p1); }
void AttackModule__hit_absolute_joint_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x88/8])(m,p1); }
void AttackModule__set_absolute_lr_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x90/8])(m,p1); }
void AttackModule__set_whole_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64,bool)>(VT(m)[0x98/8])(m,p1,p2); }
void AttackModule__sleep_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0xa0/8])(m,p1); }
u32 AttackModule__active_part_num_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<u32(*)(void*)>(VT(m)[0xc0/8])(m); }
void AttackModule__set_invalid_invincible_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64,bool)>(VT(m)[0xd0/8])(m,p1,p2); }
void AttackModule__set_invalid_xlu_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64,bool)>(VT(m)[0xe0/8])(m,p1,p2); }
void AttackModule__set_power_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64,bool)>(VT(m)[0xf8/8])(m,p1,p2); }
void AttackModule__add_power_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64,bool)>(VT(m)[0x100/8])(m,p1,p2); }
void AttackModule__set_vector_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,bool p3) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64,u64,bool)>(VT(m)[0x108/8])(m,p1,p2,p3); }
u32 AttackModule__size_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); return reinterpret_cast<u32(*)(void*,u64)>(VT(m)[0x110/8])(m,p1); }
void AttackModule__set_size_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x118/8])(m,p1); }
void AttackModule__set_target_category_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x120/8])(m,p1); }
void AttackModule__off_target_kind_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x128/8])(m,p1); }
void AttackModule__set_offset_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x130/8])(m,p1); }
void AttackModule__set_offset2_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x138/8])(m,p1); }
void AttackModule__get_offset2_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64,bool)>(VT(m)[0x140/8])(m,p1,p2); }
void AttackModule__set_node_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x148/8])(m,p1); }
void AttackModule__set_serial_hit_frame_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x150/8])(m,p1); }
void AttackModule__get_power_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2,bool p3) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64,bool,bool)>(VT(m)[0x158/8])(m,p1,p2,p3); }
u32 AttackModule__group_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); return reinterpret_cast<u32(*)(void*,u64)>(VT(m)[0x168/8])(m,p1); }
f32 AttackModule__reaction_effect_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*,u64,bool)>(VT(m)[0x170/8])(m,p1,p2); }
void AttackModule__set_reaction_effect_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,bool p3) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64,u64,bool)>(VT(m)[0x178/8])(m,p1,p2,p3); }
f32 AttackModule__reaction_fix_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*,u64,bool)>(VT(m)[0x180/8])(m,p1,p2); }
void AttackModule__set_reaction_fix_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,bool p3) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64,u64,bool)>(VT(m)[0x188/8])(m,p1,p2,p3); }
f32 AttackModule__reaction_add_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*,u64,bool)>(VT(m)[0x190/8])(m,p1,p2); }
void AttackModule__set_reaction_add_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,bool p3) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64,u64,bool)>(VT(m)[0x198/8])(m,p1,p2,p3); }
f32 AttackModule__reaction_mul_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*,u64)>(VT(m)[0x1a0/8])(m,p1); }
void AttackModule__set_pos_x_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x1a8/8])(m,p1); }
f32 AttackModule__pos_x_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*,u64,bool)>(VT(m)[0x1b0/8])(m,p1,p2); }
f32 AttackModule__pos_x_2_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*,u64)>(VT(m)[0x1b8/8])(m,p1); }
f32 AttackModule__pos_y_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*,u64)>(VT(m)[0x1c0/8])(m,p1); }
void* AttackModule__center_pos_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2) { auto* m=AT(a); return reinterpret_cast<void*(*)(void*,u64,bool)>(VT(m)[0x1c8/8])(m,p1,p2); }
f32 AttackModule__speed_x_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*,u64)>(VT(m)[0x1d0/8])(m,p1); }
void AttackModule__set_speed_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x1e0/8])(m,p1); }
void* AttackModule__attack_data_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2) { auto* m=AT(a); return reinterpret_cast<void*(*)(void*,u64,bool)>(VT(m)[0x1e8/8])(m,p1,p2); }
void AttackModule__set_power_mul_status_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x1f0/8])(m,p1); }
f32 AttackModule__power_mul_status_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x1f8/8])(m); }
void AttackModule__set_power_add_status_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x200/8])(m,p1); }
f32 AttackModule__power_add_status_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x208/8])(m); }
void AttackModule__set_power_speed_status_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x210/8])(m,p1); }
f32 AttackModule__power_speed_status_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x218/8])(m); }
void AttackModule__set_power_speed_limit_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x220/8])(m,p1); }
f32 AttackModule__power_speed_limit_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x228/8])(m); }
void AttackModule__set_power_mul_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x230/8])(m,p1); }
f32 AttackModule__power_mul_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x238/8])(m); }
void AttackModule__set_power_mul_2nd_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x240/8])(m,p1); }
f32 AttackModule__power_mul_2nd_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x248/8])(m); }
void AttackModule__set_power_mul_3rd_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x250/8])(m,p1); }
f32 AttackModule__power_mul_3rd_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x258/8])(m); }
void AttackModule__set_power_mul_4th_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x260/8])(m,p1); }
f32 AttackModule__power_mul_4th_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x268/8])(m); }
// Batch 2
void AttackModule__set_power_mul_5th_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x270/8])(m,p1); }
f32 AttackModule__power_mul_5th_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x278/8])(m); }
void AttackModule__set_customize_attack_ratio_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x290/8])(m,p1); }
f32 AttackModule__customize_attack_ratio_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x298/8])(m); }
void AttackModule__set_reaction_mul_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x2a0/8])(m,p1); }
void AttackModule__set_reaction_mul_2nd_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x2a8/8])(m,p1); }
f32 AttackModule__reaction_mul_2nd_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x2b0/8])(m); }
void AttackModule__set_reaction_mul_3rd_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x2b8/8])(m,p1); }
f32 AttackModule__reaction_mul_3rd_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x2c0/8])(m); }
void AttackModule__set_reaction_mul_4th_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x2c8/8])(m,p1); }
f32 AttackModule__reaction_mul_4th_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x2d0/8])(m); }
void AttackModule__set_damage_reaction_mul_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x328/8])(m,p1); }
f32 AttackModule__get_damage_reaction_mul_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x330/8])(m); }
void AttackModule__set_shield_stiff_mul_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x348/8])(m,p1); }
f32 AttackModule__shield_stiff_mul_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x350/8])(m); }
void AttackModule__set_ignore_just_shield_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x368/8])(m,p1); }
f32 AttackModule__get_lr_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*,u64,bool)>(VT(m)[0x378/8])(m,p1,p2); }
u32 AttackModule__part_size_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<u32(*)(void*)>(VT(m)[0x380/8])(m); }
void* AttackModule__ref_log_group_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); return reinterpret_cast<void*(*)(void*,u64)>(VT(m)[0x3a0/8])(m,p1); }
void AttackModule__un_ref_log_group_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x3a8/8])(m,p1); }
void* AttackModule__get_inflict_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); return reinterpret_cast<void*(*)(void*,u64)>(VT(m)[0x3b8/8])(m,p1); }
void* AttackModule__get_inflict_status_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); return reinterpret_cast<void*(*)(void*,u64)>(VT(m)[0x3c8/8])(m,p1); }
void AttackModule__set_indirect_info_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,bool p3,bool p4) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64,u64,bool,bool)>(VT(m)[0x3d8/8])(m,p1,p2,p3,p4); }
u32 AttackModule__indirect_object_id_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<u32(*)(void*)>(VT(m)[0x3e0/8])(m); }
u32 AttackModule__indirect_team_no_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<u32(*)(void*)>(VT(m)[0x3e8/8])(m); }
void AttackModule__set_restrict_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x430/8])(m,p1); }
void AttackModule__set_no_attacker_log_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2,bool p3) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64,bool,bool)>(VT(m)[0x438/8])(m,p1,p2,p3); }
void AttackModule__set_catch_only_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2,bool p3) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64,bool,bool)>(VT(m)[0x440/8])(m,p1,p2,p3); }
void AttackModule__set_catch_only_all_impl(BattleObjectModuleAccessor* a,bool p1,bool p2) { auto* m=AT(a); reinterpret_cast<void(*)(void*,bool,bool)>(VT(m)[0x448/8])(m,p1,p2); }
void AttackModule__set_attack_keep_rumble_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64,bool)>(VT(m)[0x450/8])(m,p1,p2); }
f32 AttackModule__get_power_up_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x458/8])(m); }
void AttackModule__set_power_up_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x460/8])(m,p1); }
u32 AttackModule__get_power_up_attr_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<u32(*)(void*)>(VT(m)[0x468/8])(m); }
void AttackModule__set_power_up_attr_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x470/8])(m,p1); }
u32 AttackModule__get_attacker_attribute_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<u32(*)(void*)>(VT(m)[0x478/8])(m); }
void AttackModule__set_attacker_attribute_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x480/8])(m,p1); }
f32 AttackModule__get_power_apply_defense_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*,u64)>(VT(m)[0x488/8])(m,p1); }
void* AttackModule__attack_reference_pos_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); return reinterpret_cast<void*(*)(void*,u64)>(VT(m)[0x4a8/8])(m,p1); }
f32 AttackModule__attack_direction_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*,u64)>(VT(m)[0x4b0/8])(m,p1); }
void AttackModule__set_attack_reference_joint_id_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x4c8/8])(m,p1); }
void AttackModule__set_overlap_hit_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x4e0/8])(m,p1); }
void AttackModule__set_no_team_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x4e8/8])(m,p1); }
void AttackModule__disable_tip_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x4f8/8])(m,p1); }
void AttackModule__relocate_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x500/8])(m,p1); }
void AttackModule__set_lerp_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x508/8])(m,p1); }
void AttackModule__clear_lerp_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x510/8])(m,p1); }
void AttackModule__set_lerp_ratio_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x518/8])(m,p1); }
void AttackModule__set_attack_power_mul_pattern_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x520/8])(m,p1); }
f32 AttackModule__get_attack_power_mul_pattern_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x528/8])(m); }
void AttackModule__set_attack_power_mul_scale_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x530/8])(m,p1); }
f32 AttackModule__get_attack_power_mul_scale_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x538/8])(m); }
void AttackModule__set_lr_check_default_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x540/8])(m,p1); }
u32 AttackModule__lr_check_default_impl(BattleObjectModuleAccessor* a) { auto* m=AT(a); return reinterpret_cast<u32(*)(void*)>(VT(m)[0x548/8])(m); }
void AttackModule__set_lr_check_front_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x550/8])(m,p1); }
void AttackModule__set_lr_check_back_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x558/8])(m,p1); }
void AttackModule__set_lr_check_front_lr_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x560/8])(m,p1); }
void AttackModule__set_disable_power_add_status_zero_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x568/8])(m,p1); }
void AttackModule__reset_status_attack_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x570/8])(m,p1); }
f32 AttackModule__damage_shake_scale_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=AT(a); return reinterpret_cast<f32(*)(void*,u64)>(VT(m)[0x578/8])(m,p1); }
} // namespace app::lua_bind
