#include "app/BattleObjectModuleAccessor.h"
#define MO(a) (a->motion_module)
#define VT(m) (*reinterpret_cast<void***>(m))
namespace app::lua_bind {
// change_motion variants
void MotionModule__change_motion_impl(BattleObjectModuleAccessor* a,u64 h,f32 r,bool p1,bool p2,bool p3) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64,f32,bool,bool,bool)>(VT(m)[0xe0/8])(m,h,r,p1,p2,p3); }
void MotionModule__change_motion_inherit_frame_impl(BattleObjectModuleAccessor* a,u64 h,bool p1,bool p2) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64,bool,bool)>(VT(m)[0xe8/8])(m,h,p1,p2); }
void MotionModule__change_motion_inherit_frame_keep_rate_impl(BattleObjectModuleAccessor* a,u64 h) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0xf0/8])(m,h); }
void MotionModule__change_motion_force_inherit_frame_impl(BattleObjectModuleAccessor* a,u64 h) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0xf8/8])(m,h); }
void MotionModule__change_motion_kind_impl(BattleObjectModuleAccessor* a,u64 h) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x100/8])(m,h); }
void MotionModule__add_motion_2nd_impl(BattleObjectModuleAccessor* a,u64 h,bool p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64,bool)>(VT(m)[0x108/8])(m,h,p1); }
// getters
f32 MotionModule__get_weight_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x118/8])(m); }
bool MotionModule__is_blend_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x128/8])(m); }
bool MotionModule__is_changing_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x130/8])(m); }
u64 MotionModule__motion_kind_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<u64(*)(void*)>(VT(m)[0x138/8])(m); }
f32 MotionModule__rate_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x140/8])(m); }
f32 MotionModule__rate_2nd_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x150/8])(m); }
f32 MotionModule__frame_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x160/8])(m); }
f32 MotionModule__prev_frame_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x168/8])(m); }
void MotionModule__set_frame_impl(BattleObjectModuleAccessor* a,f32 f) { auto* m=MO(a); reinterpret_cast<void(*)(void*,f32)>(VT(m)[0x170/8])(m,f); }
void MotionModule__set_frame_sync_anim_cmd_impl(BattleObjectModuleAccessor* a,f32 f,bool p1,bool p2,bool p3) { auto* m=MO(a); reinterpret_cast<void(*)(void*,f32,bool,bool,bool)>(VT(m)[0x178/8])(m,f,p1,p2,p3); }
f32 MotionModule__end_frame_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x180/8])(m); }
f32 MotionModule__end_frame_from_hash_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x188/8])(m); }
void MotionModule__set_frame_2nd_impl(BattleObjectModuleAccessor* a,f32 f) { auto* m=MO(a); reinterpret_cast<void(*)(void*,f32)>(VT(m)[0x190/8])(m,f); }
f32 MotionModule__frame_2nd_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x198/8])(m); }
void* MotionModule__joint_local_tra_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=MO(a); return reinterpret_cast<void*(*)(void*,u64)>(VT(m)[0x1b8/8])(m,p1); }
bool MotionModule__is_end_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x1c8/8])(m); }
bool MotionModule__is_looped_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x1d0/8])(m); }
bool MotionModule__is_loop_flag_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x1f8/8])(m); }
u64 MotionModule__resource_id_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<u64(*)(void*)>(VT(m)[0x280/8])(m); }
u64 MotionModule__animcmd_name_hash_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<u64(*)(void*)>(VT(m)[0x288/8])(m); }
f32 MotionModule__prev_weight_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x2a0/8])(m); }
void MotionModule__calc_joint_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x2b8/8])(m,p1); }
void* MotionModule__joint_local_rotation_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=MO(a); return reinterpret_cast<void*(*)(void*,u64)>(VT(m)[0x2d0/8])(m,p1); }
f32 MotionModule__end_frame_2nd_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x2e0/8])(m); }
u64 MotionModule__motion_kind_2nd_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<u64(*)(void*)>(VT(m)[0x2f0/8])(m); }
bool MotionModule__is_flag_link_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x2f8/8])(m); }
bool MotionModule__is_flag_start_1_frame_from_motion_kind_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x300/8])(m); }
bool MotionModule__is_flag_start_1_frame_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x308/8])(m); }
bool MotionModule__is_flag_start_1_frame_2nd_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x310/8])(m); }
void MotionModule__joint_rotate_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x318/8])(m,p1); }
void MotionModule__add_motion_partial_impl(BattleObjectModuleAccessor* a,u64 p1,u64 p2,f32 p3,bool p4,bool p5,bool p6,bool p7,bool p8) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64,u64,f32,bool,bool,bool,bool,bool)>(VT(m)[0x320/8])(m,p1,p2,p3,p4,p5,p6,p7,p8); }
void MotionModule__remove_motion_partial_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x328/8])(m,p1); }
void MotionModule__remove_motion_partial_comp_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); reinterpret_cast<void(*)(void*)>(VT(m)[0x338/8])(m); }
u64 MotionModule__motion_kind_partial_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<u64(*)(void*)>(VT(m)[0x340/8])(m); }
bool MotionModule__is_end_partial_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x348/8])(m); }
f32 MotionModule__end_frame_partial_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x350/8])(m); }
f32 MotionModule__rate_partial_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x360/8])(m); }
f32 MotionModule__frame_partial_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x368/8])(m); }
f32 MotionModule__prev_frame_partial_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x370/8])(m); }
void MotionModule__set_frame_partial_impl(BattleObjectModuleAccessor* a,f32 f) { auto* m=MO(a); reinterpret_cast<void(*)(void*,f32)>(VT(m)[0x378/8])(m,f); }
void MotionModule__set_frame_partial_sync_anim_cmd_impl(BattleObjectModuleAccessor* a,f32 f) { auto* m=MO(a); reinterpret_cast<void(*)(void*,f32)>(VT(m)[0x380/8])(m,f); }
bool MotionModule__is_flag_start_1_frame_partial_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x388/8])(m); }
bool MotionModule__is_flip_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x390/8])(m); }
void MotionModule__set_flip_impl(BattleObjectModuleAccessor* a,u64 p1,bool p2,bool p3,bool p4) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64,bool,bool,bool)>(VT(m)[0x3a0/8])(m,p1,p2,p3,p4); }
void MotionModule__set_link_flip_target_joint_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x3a8/8])(m,p1); }
void MotionModule__set_frame_material_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x3b0/8])(m,p1); }
void MotionModule__set_loop_flag_material_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x3c0/8])(m,p1); }
void MotionModule__set_helper_calculation_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x3d0/8])(m,p1); }
void MotionModule__set_recalc_ik_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x420/8])(m,p1); }
bool MotionModule__is_no_comp_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x440/8])(m); }
void MotionModule__set_kind_offset_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x448/8])(m,p1); }
void MotionModule__enable_shift_material_animation_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x468/8])(m,p1); }
bool MotionModule__is_flip_resource_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x4a0/8])(m); }
void MotionModule__set_force_progress_2nd_weight_impl(BattleObjectModuleAccessor* a,f32 f) { auto* m=MO(a); reinterpret_cast<void(*)(void*,f32)>(VT(m)[0x4f8/8])(m,f); }
void MotionModule__clear_joint_srt_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x500/8])(m,p1); }
void MotionModule__set_keep_pose_change_motion_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x588/8])(m,p1); }
void MotionModule__enable_remove_2nd_change_motion_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x5b8/8])(m,p1); }
void MotionModule__enable_set_frame_2nd_partial_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x5c0/8])(m,p1); }
void MotionModule__set_frame_partial_sync_anim_cmd_revised_impl(BattleObjectModuleAccessor* a,f32 f) { auto* m=MO(a); reinterpret_cast<void(*)(void*,f32)>(VT(m)[0x5c8/8])(m,f); }
void MotionModule__set_keep_pose_change_motion_with_update_pose_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x5e0/8])(m,p1); }
void MotionModule__set_animcmd_done_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x5f8/8])(m,p1); }
void MotionModule__set_link_no_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x600/8])(m,p1); }
// Missing from earlier: is_anim_resource
bool MotionModule__is_anim_resource_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=MO(a); return reinterpret_cast<bool(*)(void*,u64)>(VT(m)[0x270/8])(m,p1); }
bool MotionModule__is_end_2nd_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x2e8/8])(m); }
f32 MotionModule__get_frame_material_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x3c8/8])(m); }
// Remaining MotionModule dispatchers
void MotionModule__change_motion_2nd_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x110/8])(m,p1); }
f32 MotionModule__get_weight_2nd_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x120/8])(m); }
bool MotionModule__is_changing_2nd_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x148/8])(m); }
u64 MotionModule__motion_kind_prev_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<u64(*)(void*)>(VT(m)[0x158/8])(m); }
void MotionModule__set_rate_2nd_impl(BattleObjectModuleAccessor* a,f32 f,bool p1,bool p2) { auto* m=MO(a); reinterpret_cast<void(*)(void*,f32,bool,bool)>(VT(m)[0x1a0/8])(m,f,p1,p2); }
void MotionModule__set_rate_partial_impl(BattleObjectModuleAccessor* a,f32 f,bool p1,bool p2) { auto* m=MO(a); reinterpret_cast<void(*)(void*,f32,bool,bool)>(VT(m)[0x1a8/8])(m,f,p1,p2); }
f32 MotionModule__prev_frame_2nd_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x1c0/8])(m); }
bool MotionModule__is_interpreting_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x218/8])(m); }
bool MotionModule__is_interpreting_2nd_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x228/8])(m); }
bool MotionModule__is_interpreting_partial_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x238/8])(m); }
void MotionModule__set_rate_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x240/8])(m,p1); }
u64 MotionModule__trans_hash_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<u64(*)(void*)>(VT(m)[0x298/8])(m); }
u64 MotionModule__body_hash_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<u64(*)(void*)>(VT(m)[0x2b0/8])(m); }
void* MotionModule__joint_local_scale_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=MO(a); return reinterpret_cast<void*(*)(void*,u64)>(VT(m)[0x2c0/8])(m,p1); }
void* MotionModule__joint_local_tra_2nd_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=MO(a); return reinterpret_cast<void*(*)(void*,u64)>(VT(m)[0x2d8/8])(m,p1); }
f32 MotionModule__rate_2nd_partial_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<f32(*)(void*)>(VT(m)[0x358/8])(m); }
void MotionModule__set_frame_material_2nd_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x3b8/8])(m,p1); }
void MotionModule__set_helper_calculation_2nd_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x3d8/8])(m,p1); }
void MotionModule__set_frame_looped_flag_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x3f0/8])(m,p1); }
bool MotionModule__is_flag_disable_change_motion_impl(BattleObjectModuleAccessor* a) { auto* m=MO(a); return reinterpret_cast<bool(*)(void*)>(VT(m)[0x3f8/8])(m); }
void MotionModule__set_flag_disable_change_motion_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x410/8])(m,p1); }
void MotionModule__set_no_comp_2nd_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x438/8])(m,p1); }
void MotionModule__set_kind_offset_2nd_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x470/8])(m,p1); }
void MotionModule__enable_shift_material_animation_2nd_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x478/8])(m,p1); }
void MotionModule__set_force_progress_2nd_weight_2nd_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x4c0/8])(m,p1); }
void MotionModule__set_keep_pose_change_motion_2nd_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x528/8])(m,p1); }
void MotionModule__set_keep_anim_frame_change_motion_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x590/8])(m,p1); }
void MotionModule__set_keep_anim_frame_change_motion_2nd_impl(BattleObjectModuleAccessor* a,u64 p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,u64)>(VT(m)[0x598/8])(m,p1); }
void MotionModule__set_keep_anim_frame_change_motion_partial_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x5a0/8])(m,p1); }
void MotionModule__set_link_no_2nd_impl(BattleObjectModuleAccessor* a,bool p1) { auto* m=MO(a); reinterpret_cast<void(*)(void*,bool)>(VT(m)[0x5d0/8])(m,p1); }
} // namespace app::lua_bind
