#include "types.h"

// Engine utility functions — Initialize, Finalize, Set*, Get*, thunk_*, etc.
// AUTO-GENERATED by tools/gen_engine_functions.py — do not hand-edit.
//
// Generated: 34 functions  |  Skipped: 1111 (no recognized pattern)

namespace app::lua_bind {

// AUTO-GENERATED EASY functions

// 0x7100031070  [str-xzr-ret]  SetDefault
void SetDefault_31070(void* obj) { *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x0) = 0; }

// 0x71000310a0  [movz-stp-ret]  SetDefault
void SetDefault_310a0(void* obj) { *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x0) = 0x22; *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x8) = 0; }

// 0x7100031240  [orr-str-strb-ret]  SetDefault
void SetDefault_31240(void* obj) { *reinterpret_cast<u32*>(reinterpret_cast<u8*>(obj) + 0x0) = 0x7000000; *reinterpret_cast<u8*>(reinterpret_cast<u8*>(obj) + 0x4) = 0; }

// 0x71000312a0  [multi-zero]  SetDefault
void SetDefault_312a0(void* obj) { *reinterpret_cast<u32*>(reinterpret_cast<u8*>(obj) + 0x4) = 0; *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x8) = 0; *reinterpret_cast<u8*>(reinterpret_cast<u8*>(obj) + 0x0) = 0; }

// 0x71000338e0  [orr-imm-ret]  GetPoolMemorySizeGranularity
u32 GetPoolMemorySizeGranularity_338e0(void* obj) { return 0x1000; }

// 0x71000374c0  [noop]  GetBufferAddress
void GetBufferAddress_374c0(void* obj) { }

// 0x710003a610  [noop]  GetRequiredMemorySize
void GetRequiredMemorySize_3a610(void* obj) { }

// 0x710003e210  [deref-field]  GetFrameSize
u16 GetFrameSize_3e210(void* obj) { auto* p = *reinterpret_cast<u8**>(reinterpret_cast<u8*>(obj) + 0x18); return *reinterpret_cast<u16*>(p + 0x8); }

// 0x71000441f0  [multi-zero]  SetDefault
void SetDefault_441f0(void* obj) { *reinterpret_cast<u16*>(reinterpret_cast<u8*>(obj) + 0x4) = 0; *reinterpret_cast<u32*>(reinterpret_cast<u8*>(obj) + 0x0) = 0; *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x8) = 0; *reinterpret_cast<u32*>(reinterpret_cast<u8*>(obj) + 0x10) = 0; }

// 0x7100044470  [multi-zero]  Initialize
void Initialize_44470(void* obj) { *reinterpret_cast<u16*>(reinterpret_cast<u8*>(obj) + 0x0) = 0; *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x8) = 0; }

// 0x7100088970  [str-w1-ret]  SetDrawPath
void SetDrawPath_88970(void* obj, u32 val) { *reinterpret_cast<u32*>(reinterpret_cast<u8*>(obj) + 0x400) = val; }

// 0x71000b8870  [orr-imm-ret]  GetSerializedSize
u32 GetSerializedSize_b8870(void* obj) { return 0x10; }

// 0x71000b8bc0  [orr-imm-ret]  GetSerializedSize
u32 GetSerializedSize_b8bc0(void* obj) { return 0x10; }

// 0x71000bae40  [ldr-x0-ret]  GetBuffer
u64 GetBuffer_bae40(void* obj) { return *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x8); }

// 0x71000c03c0  [multi-zero]  Finalize
void Finalize_c03c0(void* obj) { *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x70) = 0; *reinterpret_cast<u32*>(reinterpret_cast<u8*>(obj) + 0x78) = 0; }

// 0x710013dcc0  [multi-zero]  Reset
void Reset_13dcc0(void* obj) { *reinterpret_cast<u16*>(reinterpret_cast<u8*>(obj) + 0x8) = 0; *reinterpret_cast<u8*>(reinterpret_cast<u8*>(obj) + 0xa) = 0; *reinterpret_cast<u16*>(reinterpret_cast<u8*>(obj) + 0xc) = 0; *reinterpret_cast<u8*>(reinterpret_cast<u8*>(obj) + 0xe) = 0; }

// 0x710013f9b0  [multi-zero]  Reset
void Reset_13f9b0(void* obj) { *reinterpret_cast<u32*>(reinterpret_cast<u8*>(obj) + 0x10) = 0; *reinterpret_cast<u16*>(reinterpret_cast<u8*>(obj) + 0x14) = 0; *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x8) = 0; }

// 0x7100146be0  [ldr-w0-ret]  GetStationNum
u32 GetStationNum_146be0(void* obj) { return *reinterpret_cast<u32*>(reinterpret_cast<u8*>(obj) + 0x1a8); }

// 0x7100161fa0  [ldr-x0-ret]  GetStation
u64 GetStation_161fa0(void* obj) { return *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x90); }

// 0x7100162480  [ldr-x0-ret]  GetNetworkFactory
u64 GetNetworkFactory_162480(void* obj) { return *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x8); }

// 0x71001aeaf0  [multi-zero]  ClearBaseTime
void ClearBaseTime_1aeaf0(void* obj) { *reinterpret_cast<u8*>(reinterpret_cast<u8*>(obj) + 0x8) = 0; *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x0) = 0; }

// 0x71001b6060  [ldr-x0-ret]  GetBuffer
u64 GetBuffer_1b6060(void* obj) { return *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x0); }

// 0x71001b6070  [ldr-x0-ret]  GetBufferSize
u64 GetBufferSize_1b6070(void* obj) { return *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x8); }

// 0x71001ce080  [orr-imm-ret]  GetChecksumLength
u32 GetChecksumLength_1ce080(void* obj) { return 0x10; }

// 0x710022b380  [strh-w1-ret]  SetProtocolID
void SetProtocolID_22b380(void* obj, u16 val) { *reinterpret_cast<u16*>(reinterpret_cast<u8*>(obj) + 0x48) = val; }

// 0x71002b4760  [noop]  thunk_FUN_71002b62f0
void thunk_FUN_71002b62f0_2b4760(void* obj) { }

// 0x71020b1920  [vtable-dispatch]  LinkEventFinal__load_from_l2c_table_impl
void* LinkEventFinal__load_from_l2c_table_impl_20b1920(void* obj, u64 p1) { return reinterpret_cast<void*(*)(void*, u64)>((*reinterpret_cast<void***>(obj))[0x38/8])(obj, p1); }

// 0x71020bbed0  [vtable-dispatch]  OnCalcParamEvent__load_from_l2c_table_impl
void* OnCalcParamEvent__load_from_l2c_table_impl_20bbed0(void* obj, u64 p1) { return reinterpret_cast<void*(*)(void*, u64)>((*reinterpret_cast<void***>(obj))[0x38/8])(obj, p1); }

// 0x710216fed0  [vtable-dispatch]  FighterPikminLinkEventWeaponPikminSetInt__load_from_l2c_table_impl
void* FighterPikminLinkEventWeaponPikminSetInt__load_from_l2c_table_impl_216fed0(void* obj, u64 p1) { return reinterpret_cast<void*(*)(void*, u64)>((*reinterpret_cast<void***>(obj))[0x38/8])(obj, p1); }

// 0x7102170bd0  [vtable-dispatch]  FighterPikminLinkEventWeaponPikminSetFloat__load_from_l2c_table_impl
void* FighterPikminLinkEventWeaponPikminSetFloat__load_from_l2c_table_impl_2170bd0(void* obj, u64 p1) { return reinterpret_cast<void*(*)(void*, u64)>((*reinterpret_cast<void***>(obj))[0x38/8])(obj, p1); }

// 0x71021718c0  [vtable-dispatch]  FighterPikminLinkEventWeaponPikminSetPowerMulStatus__load_from_l2c_table_impl
void* FighterPikminLinkEventWeaponPikminSetPowerMulStatus__load_from_l2c_table_impl_21718c0(void* obj, u64 p1) { return reinterpret_cast<void*(*)(void*, u64)>((*reinterpret_cast<void***>(obj))[0x38/8])(obj, p1); }

// 0x7102195b20  [vtable-dispatch]  FighterRyuLinkEventFinalDeadDamage__load_from_l2c_table_impl
void* FighterRyuLinkEventFinalDeadDamage__load_from_l2c_table_impl_2195b20(void* obj, u64 p1) { return reinterpret_cast<void*(*)(void*, u64)>((*reinterpret_cast<void***>(obj))[0x38/8])(obj, p1); }

// 0x7102196640  [vtable-dispatch]  FighterRyuLinkEventFinalMoveTarget__load_from_l2c_table_impl
void* FighterRyuLinkEventFinalMoveTarget__load_from_l2c_table_impl_2196640(void* obj, u64 p1) { return reinterpret_cast<void*(*)(void*, u64)>((*reinterpret_cast<void***>(obj))[0x38/8])(obj, p1); }

// 0x71021992c0  [vtable-dispatch]  FighterCloudLinkEventFinal__load_from_l2c_table_impl
void* FighterCloudLinkEventFinal__load_from_l2c_table_impl_21992c0(void* obj, u64 p1) { return reinterpret_cast<void*(*)(void*, u64)>((*reinterpret_cast<void***>(obj))[0x38/8])(obj, p1); }

} // namespace app::lua_bind
