#include "types.h"

// Engine utility functions — Initialize, Finalize, Set*, Get*, thunk_*, etc.
// AUTO-GENERATED by tools/gen_engine_functions.py — do not hand-edit.
//
// Generated: 35 functions  |  Skipped: 1110 (no recognized pattern)

namespace app::lua_bind {

// AUTO-GENERATED EASY functions

// 0x7100031070  [str-xzr-ret]  SetDefault
void SetDefault_31070(void* obj) { *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x0) = 0; }

// 0x71000310a0  [movz-stp-ret]  SetDefault
void SetDefault_310a0(void* obj) { *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x0) = 0x22; *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x8) = 0; }

// 0x7100031240  [orr-str-strb-ret]  SetDefault
void SetDefault_31240(void* obj) { *reinterpret_cast<u32*>(reinterpret_cast<u8*>(obj) + 0x0) = 0x7000000; *reinterpret_cast<u8*>(reinterpret_cast<u8*>(obj) + 0x4) = 0; }

// 0x71000312a0  [multi-zero]  SetDefault
void SetDefault_312a0(void* obj) { *reinterpret_cast<u32*>(reinterpret_cast<u8*>(obj) + 0x4) = 0; *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x8) = 0; *reinterpret_cast<u8*>(reinterpret_cast<u8*>(obj) + 0x0) = 0; }

// 0x71000338e0  [orr-imm-ret]  GetPoolMemorySizeGranularity
u32 GetPoolMemorySizeGranularity_338e0(void* obj) { return 0x1000; }

// 0x71000374c0  [noop]  GetBufferAddress
void GetBufferAddress_374c0(void* obj) { }

// 0x7100039590  [ldrb-lsl-ret]  GetRequiredMemorySize
u64 GetRequiredMemorySize_39590(void* obj) { u8 t = *reinterpret_cast<u8*>(reinterpret_cast<u8*>(obj)); return (u64)t << 3; }

// 0x710003a610  [noop]  GetRequiredMemorySize
void GetRequiredMemorySize_3a610(void* obj) { }

// 0x710003e210  [deref-field]  GetFrameSize
u16 GetFrameSize_3e210(void* obj) { auto* p = *reinterpret_cast<u8**>(reinterpret_cast<u8*>(obj) + 0x18); return *reinterpret_cast<u16*>(p + 0x8); }

// 0x71000441f0  [multi-zero]  SetDefault
void SetDefault_441f0(void* obj) { *reinterpret_cast<u16*>(reinterpret_cast<u8*>(obj) + 0x4) = 0; *reinterpret_cast<u32*>(reinterpret_cast<u8*>(obj) + 0x0) = 0; *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x8) = 0; *reinterpret_cast<u32*>(reinterpret_cast<u8*>(obj) + 0x10) = 0; }

// 0x7100044470  [multi-zero]  Initialize
void Initialize_44470(void* obj) { *reinterpret_cast<u16*>(reinterpret_cast<u8*>(obj) + 0x0) = 0; *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x8) = 0; }

// 0x7100088970  [str-w1-ret]  SetDrawPath
void SetDrawPath_88970(void* obj, u32 val) { *reinterpret_cast<u32*>(reinterpret_cast<u8*>(obj) + 0x400) = val; }

// 0x71000b8870  [orr-imm-ret]  GetSerializedSize
u32 GetSerializedSize_b8870(void* obj) { return 0x10; }

// 0x71000b8bc0  [orr-imm-ret]  GetSerializedSize
u32 GetSerializedSize_b8bc0(void* obj) { return 0x10; }

// 0x71000bae40  [ldr-x0-ret]  GetBuffer
u64 GetBuffer_bae40(void* obj) { return *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x8); }

// 0x71000c03c0  [multi-zero]  Finalize
void Finalize_c03c0(void* obj) { *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x70) = 0; *reinterpret_cast<u32*>(reinterpret_cast<u8*>(obj) + 0x78) = 0; }

// 0x710013dcc0  [multi-zero]  Reset
void Reset_13dcc0(void* obj) { *reinterpret_cast<u16*>(reinterpret_cast<u8*>(obj) + 0x8) = 0; *reinterpret_cast<u8*>(reinterpret_cast<u8*>(obj) + 0xa) = 0; *reinterpret_cast<u16*>(reinterpret_cast<u8*>(obj) + 0xc) = 0; *reinterpret_cast<u8*>(reinterpret_cast<u8*>(obj) + 0xe) = 0; }

// 0x710013f9b0  [multi-zero]  Reset
void Reset_13f9b0(void* obj) { *reinterpret_cast<u32*>(reinterpret_cast<u8*>(obj) + 0x10) = 0; *reinterpret_cast<u16*>(reinterpret_cast<u8*>(obj) + 0x14) = 0; *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x8) = 0; }

// 0x7100146be0  [ldr-w0-ret]  GetStationNum
u32 GetStationNum_146be0(void* obj) { return *reinterpret_cast<u32*>(reinterpret_cast<u8*>(obj) + 0x1a8); }

// 0x7100161fa0  [ldr-x0-ret]  GetStation
u64 GetStation_161fa0(void* obj) { return *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x90); }

// 0x7100162480  [ldr-x0-ret]  GetNetworkFactory
u64 GetNetworkFactory_162480(void* obj) { return *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x8); }

// 0x71001aeaf0  [multi-zero]  ClearBaseTime
void ClearBaseTime_1aeaf0(void* obj) { *reinterpret_cast<u8*>(reinterpret_cast<u8*>(obj) + 0x8) = 0; *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x0) = 0; }

// 0x71001b6060  [ldr-x0-ret]  GetBuffer
u64 GetBuffer_1b6060(void* obj) { return *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x0); }

// 0x71001b6070  [ldr-x0-ret]  GetBufferSize
u64 GetBufferSize_1b6070(void* obj) { return *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x8); }

// 0x71001ce080  [orr-imm-ret]  GetChecksumLength
u32 GetChecksumLength_1ce080(void* obj) { return 0x10; }

// 0x710022b380  [strh-w1-ret]  SetProtocolID
void SetProtocolID_22b380(void* obj, u16 val) { *reinterpret_cast<u16*>(reinterpret_cast<u8*>(obj) + 0x48) = val; }

// 0x71002b4760  [noop]  thunk_FUN_71002b62f0
void thunk_FUN_71002b62f0_2b4760(void* obj) { }

// 0x71020b1920  [vtable-dispatch]  LinkEventFinal__load_from_l2c_table_impl
void* LinkEventFinal__load_from_l2c_table_impl_20b1920(void* obj, u64 p1) { return reinterpret_cast<void*(*)(void*, u64)>((*reinterpret_cast<void***>(obj))[0x38/8])(obj, p1); }

// 0x71020bbed0  [vtable-dispatch]  OnCalcParamEvent__load_from_l2c_table_impl
void* OnCalcParamEvent__load_from_l2c_table_impl_20bbed0(void* obj, u64 p1) { return reinterpret_cast<void*(*)(void*, u64)>((*reinterpret_cast<void***>(obj))[0x38/8])(obj, p1); }

// 0x710216fed0  [vtable-dispatch]  FighterPikminLinkEventWeaponPikminSetInt__load_from_l2c_table_impl
void* FighterPikminLinkEventWeaponPikminSetInt__load_from_l2c_table_impl_216fed0(void* obj, u64 p1) { return reinterpret_cast<void*(*)(void*, u64)>((*reinterpret_cast<void***>(obj))[0x38/8])(obj, p1); }

// 0x7102170bd0  [vtable-dispatch]  FighterPikminLinkEventWeaponPikminSetFloat__load_from_l2c_table_impl
void* FighterPikminLinkEventWeaponPikminSetFloat__load_from_l2c_table_impl_2170bd0(void* obj, u64 p1) { return reinterpret_cast<void*(*)(void*, u64)>((*reinterpret_cast<void***>(obj))[0x38/8])(obj, p1); }

// 0x71021718c0  [vtable-dispatch]  FighterPikminLinkEventWeaponPikminSetPowerMulStatus__load_from_l2c_table_impl
void* FighterPikminLinkEventWeaponPikminSetPowerMulStatus__load_from_l2c_table_impl_21718c0(void* obj, u64 p1) { return reinterpret_cast<void*(*)(void*, u64)>((*reinterpret_cast<void***>(obj))[0x38/8])(obj, p1); }

// 0x7102195b20  [vtable-dispatch]  FighterRyuLinkEventFinalDeadDamage__load_from_l2c_table_impl
void* FighterRyuLinkEventFinalDeadDamage__load_from_l2c_table_impl_2195b20(void* obj, u64 p1) { return reinterpret_cast<void*(*)(void*, u64)>((*reinterpret_cast<void***>(obj))[0x38/8])(obj, p1); }

// 0x7102196640  [vtable-dispatch]  FighterRyuLinkEventFinalMoveTarget__load_from_l2c_table_impl
void* FighterRyuLinkEventFinalMoveTarget__load_from_l2c_table_impl_2196640(void* obj, u64 p1) { return reinterpret_cast<void*(*)(void*, u64)>((*reinterpret_cast<void***>(obj))[0x38/8])(obj, p1); }

// 0x71021992c0  [vtable-dispatch]  FighterCloudLinkEventFinal__load_from_l2c_table_impl
void* FighterCloudLinkEventFinal__load_from_l2c_table_impl_21992c0(void* obj, u64 p1) { return reinterpret_cast<void*(*)(void*, u64)>((*reinterpret_cast<void***>(obj))[0x38/8])(obj, p1); }

// MANUAL: 0x7100039e10  ViewportScissorState::GetRequiredMemorySize  (ldrh+mul-sub)
// ldrh w8,[x0,#2]; mov w9,#40; mul x8,x8,x9; sub x0,x8,#40; ret
u64 GetRequiredMemorySize_3e10(void* obj) {
    u16 n = *reinterpret_cast<u16*>(reinterpret_cast<u8*>(obj) + 2);
    return (u64)n * 0x28 - 0x28;
}

// MANUAL: 0x7100039de0  TessellationStateImpl::Initialize  (ldrh+str+orr-1+strb)
// ldrh w8,[x2]; str w8,[x0,#4]; orr w8,wzr,#1; strb w8,[x0]; ret
void Initialize_39de0(void* param_1, u64 param_2, void* param_3) {
    *reinterpret_cast<u32*>(reinterpret_cast<u8*>(param_1) + 4) = *reinterpret_cast<u16*>(param_3);
    *reinterpret_cast<u8*>(param_1) = 1;
}

// MANUAL: 0x71000b7080  ListBase::Init  (stp x0,x0,[x0]+str-wzr)
// stp x0,x0,[x0]; str wzr,[x0,#16]; ret
void Init_b7080(void* obj) {
    *reinterpret_cast<void**>(obj) = obj;
    *reinterpret_cast<void**>(reinterpret_cast<u8*>(obj) + 8) = obj;
    *reinterpret_cast<u32*>(reinterpret_cast<u8*>(obj) + 16) = 0;
}

// MANUAL: 0x710003e230  AnimTransform::SetEnabled  (and-w1-#1+strb)
// and w8,w1,#1; strb w8,[x0,#0x24]; ret
void SetEnabled_3e230(void* obj, u8 val) {
    *reinterpret_cast<u8*>(reinterpret_cast<u8*>(obj) + 0x24) = val & 1;
}

// MANUAL: 0x71000408d0  AnimResource::GetGroupCount  (ldr+cbz+ldrh-ret+mov-0+ret)
// ldr x8,[x0,#0x10]; cbz x8,+c; ldrh w0,[x8,#0xA]; ret; mov w0,wzr; ret
u16 GetGroupCount_408d0(void* obj) {
    void* p = *reinterpret_cast<void**>(reinterpret_cast<u8*>(obj) + 0x10);
    if (p == nullptr) return 0;
    return *reinterpret_cast<u16*>(reinterpret_cast<u8*>(p) + 10);
}

// MANUAL: 0x710000408f0  AnimResource::GetGroupArray  (ldr+cbz+ldr-add-ret+mov-0+ret)
// ldr x8,[x0,#0x10]; cbz x8,+10; ldr w9,[x8,#0x10]; add x0,x8,x9; ret; mov x0,xzr; ret
u64 GetGroupArray_408f0(void* obj) {
    u64 p = *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x10);
    if (p == 0) return 0;
    return p + *reinterpret_cast<u32*>(reinterpret_cast<u8*>((void*)p) + 0x10);
}

// MANUAL: 0x7100040960  AnimResource::GetAnimationShareInfoCount  (ldr+cbz+ldrh-ret+mov-0+ret)
u16 GetAnimationShareInfoCount_40960(void* obj) {
    void* p = *reinterpret_cast<void**>(reinterpret_cast<u8*>(obj) + 0x18);
    if (p == nullptr) return 0;
    return *reinterpret_cast<u16*>(reinterpret_cast<u8*>(p) + 0xC);
}

// MANUAL: 0x7100040980  AnimResource::GetAnimationShareInfoArray  (ldr+cbz+ldr-add-ret+mov-0+ret)
u64 GetAnimationShareInfoArray_40980(void* obj) {
    u64 p = *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x18);
    if (p == 0) return 0;
    return p + *reinterpret_cast<u32*>(reinterpret_cast<u8*>((void*)p) + 8);
}

// MANUAL: 0x71000446c0  detail::GetResShapeInfo  (ldr+add-uxtw+ldr+add)
// ldr x8,[x0,#0x18]; add x9,x8,w1,uxtw#2; ldr w9,[x9,#0xC]; add x0,x8,x9; ret
u64 GetResShapeInfo_446c0(void* obj, u32 idx) {
    u64 base = *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0x18);
    return base + *reinterpret_cast<u32*>(reinterpret_cast<u8*>((void*)base) + (u64)idx*4 + 0xC);
}

// MANUAL: 0x71000b4160  CallContext::InitiateCall  (orr-1+str+strb-0+orr-1+ret)
// orr w8,wzr,#1; str w8,[x0]; strb wzr,[x0,#0x28]; orr w0,wzr,#1; ret
u64 InitiateCall_b4160(void* obj) {
    *reinterpret_cast<u32*>(obj) = 1;
    *reinterpret_cast<u8*>(reinterpret_cast<u8*>(obj) + 0x28) = 0;
    return 1;
}


// MANUAL: 0x71000a4f20  nn::vfx::System::InitializeEmitter  (ldr-field+str-field)
// ldr x8,[x0,#0x8c0]; str x8,[x1,#0x98]; ret
void InitializeEmitter_a4f20(void* param_1, void* param_2) {
    *reinterpret_cast<u64*>(reinterpret_cast<u8*>(param_2) + 0x98) =
        *reinterpret_cast<u64*>(reinterpret_cast<u8*>(param_1) + 0x8c0);
}

// MANUAL: 0x7100079050  nn::font::DispStringBuffer::Finalize  (ldr+cmp-1+b.lt+str-wzr)
// ldr w8,[x0,#0x98]; cmp w8,#1; b.lt #+8; str wzr,[x0,#0x98]; ret
void Finalize_79050(void* obj) {
    if (*reinterpret_cast<s32*>(reinterpret_cast<u8*>(obj) + 0x98) > 0)
        *reinterpret_cast<u32*>(reinterpret_cast<u8*>(obj) + 0x98) = 0;
}

// MANUAL: 0x7100079070  nn::font::DispStringBuffer::GetRequiredDrawBufferSize  (ldrsw+mov-57+mul)
// ldrsw x8,[x0,#0x10]; mov w9,#57; mul x0,x8,x9; ret
u64 GetRequiredDrawBufferSize_79070(void* obj) {
    return (u64)((s64)*reinterpret_cast<s32*>(reinterpret_cast<u8*>(obj) + 0x10) * 57);
}

// MANUAL: 0x7100044d40  nn::ui2d::DrawInfo::SetGpuAccessBufferIndex  (double null-guard store)
// ldr x8,[x0,#0xc8]; cbz x8,+8; str w1,[x8,#0x30]; ldr x8,[x0,#0xd0]; cbz x8,+8; str w1,[x8,#0x30]; ret
void SetGpuAccessBufferIndex_44d40(void* obj, u32 val) {
    u64 p = *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0xc8);
    if (p != 0)
        *reinterpret_cast<u32*>(p + 0x30) = val;
    u64 q = *reinterpret_cast<u64*>(reinterpret_cast<u8*>(obj) + 0xd0);
    if (q != 0)
        *reinterpret_cast<u32*>(q + 0x30) = val;
}

// MANUAL: 0x7100054150  nn::ui2d::Material::GetConstantBufferForVertexShader  (double-deref+cbz+add)
// ldr x8,[x1,#0xc8]; ldr x8,[x8,#0x38]; cbz x8,#+10; ldr w9,[x0,#0x30]; add x0,x8,x9; ret; mov x0,xzr; ret
u64 GetConstantBufferForVertexShader_54150(void* param_1, void* param_2) {
    u64 p = *reinterpret_cast<u64*>(
        reinterpret_cast<u8*>(*reinterpret_cast<void**>(reinterpret_cast<u8*>(param_2) + 0xC8)) + 0x38);
    if (p == 0) return 0;
    return p + *reinterpret_cast<u32*>(reinterpret_cast<u8*>(param_1) + 0x30);
}

} // namespace app::lua_bind
