#include "types.h"

// Batch decompiled via Ghidra MCP — pool-b, batch 006
// Range: 0x7101000000 — 0x7101FFFFFF

// Forward declarations
[[noreturn]] extern "C" void abort();
extern "C" s32 __cxa_guard_acquire(s64 *);
extern "C" void __cxa_guard_release(s64 *);

// Data symbols — guard vars
extern u64 DAT_71052c08d0;
extern u64 DAT_71052c0900;
// Data symbols — vtable pointers
extern void *DAT_71052c08c8;
extern void *DAT_71052c0908;
// PTR_LAB targets
extern u8 PTR_LAB_7105026340;
extern u8 PTR_LAB_7105028988;

// ── __throw_out_of_range thunks ───────────────────────────────────────────────
// Each is a noreturn wrapper generated by different vector instantiations.

// 0x710104a7e4
[[noreturn]] void FUN_710104a7e4()
{
  abort();
}

// 0x710104a97c
[[noreturn]] void FUN_710104a97c()
{
  abort();
}

// 0x710104ab5c
[[noreturn]] void FUN_710104ab5c()
{
  abort();
}

// 0x710104acbc
[[noreturn]] void FUN_710104acbc()
{
  abort();
}

// 0x710104ad9c
[[noreturn]] void FUN_710104ad9c()
{
  abort();
}

// 0x710104af4c
[[noreturn]] void FUN_710104af4c()
{
  abort();
}

// 0x710104b00c
[[noreturn]] void FUN_710104b00c()
{
  abort();
}

// 0x710104b0cc
[[noreturn]] void FUN_710104b0cc()
{
  abort();
}

// 0x710106953c
[[noreturn]] void FUN_710106953c()
{
  abort();
}

// 0x71010695fc
[[noreturn]] void FUN_71010695fc()
{
  abort();
}

// 0x71010696bc
[[noreturn]] void FUN_71010696bc()
{
  abort();
}

// 0x710106977c
[[noreturn]] void FUN_710106977c()
{
  abort();
}

// 0x710106983c
[[noreturn]] void FUN_710106983c()
{
  abort();
}

// 0x71010698fc
[[noreturn]] void FUN_71010698fc()
{
  abort();
}

// 0x7101069aac
[[noreturn]] void FUN_7101069aac()
{
  abort();
}

// 0x7101069c8c
[[noreturn]] void FUN_7101069c8c()
{
  abort();
}

// 0x7101069dbc
[[noreturn]] void FUN_7101069dbc()
{
  abort();
}

// ── vtable call wrappers ──────────────────────────────────────────────────────

// 0x7101008dd0
u64 FUN_7101008dd0(u64 param_1, s64 param_2)
{
  s64 *plVar1;

  plVar1 = *(s64 **)(*(s64 *)(param_2 + 0x20) + 0x50);
  (*(void(*)(s64 *, u32))(*plVar1 + 0x110))(plVar1, 0x200000e2);
  return 1;
}

// 0x71013292b0
u32 FUN_71013292b0(u64 param_1, s64 param_2)
{
  u32 uVar1;

  uVar1 = (*(u32(*)(s64 *, u32))(*(s64 *)*(s64 **)(param_2 + 0x50) + 0x108))(
            *(s64 **)(param_2 + 0x50), 0x2100000c);
  return ~uVar1 & 1;
}

// 0x7101329670
u32 FUN_7101329670(u64 param_1, s64 param_2)
{
  u32 uVar1;

  uVar1 = (*(u32(*)(s64 *, u32))(*(s64 *)*(s64 **)(param_2 + 0x50) + 0x108))(
            *(s64 **)(param_2 + 0x50), 0x2100000c);
  return ~uVar1 & 1;
}

// 0x7101329890
u32 FUN_7101329890(u64 param_1, s64 param_2)
{
  u32 uVar1;

  uVar1 = (*(u32(*)(s64 *, u32))(*(s64 *)*(s64 **)(param_2 + 0x50) + 0x108))(
            *(s64 **)(param_2 + 0x50), 0x2100000c);
  return ~uVar1 & 1;
}

// ── Guard-init vtable setters ─────────────────────────────────────────────────

// 0x7101043990
void FUN_7101043990(u64 param_1, s64 param_2)
{
  s32 iVar1;

  if ((DAT_71052c08d0 & 1) == 0) {
    iVar1 = __cxa_guard_acquire((s64 *)&DAT_71052c08d0);
    if (iVar1 != 0) {
      DAT_71052c08c8 = &PTR_LAB_7105026340;
      __cxa_guard_release((s64 *)&DAT_71052c08d0);
    }
  }
  *(void ***)(param_2 + 0x180) = &DAT_71052c08c8;
  return;
}

// 0x710105bc40
void FUN_710105bc40(u64 param_1, s64 param_2)
{
  s32 iVar1;

  if ((DAT_71052c0900 & 1) == 0) {
    iVar1 = __cxa_guard_acquire((s64 *)&DAT_71052c0900);
    if (iVar1 != 0) {
      DAT_71052c0908 = &PTR_LAB_7105028988;
      __cxa_guard_release((s64 *)&DAT_71052c0900);
    }
  }
  *(void ***)(param_2 + 0x318) = &DAT_71052c0908;
  *(u8 *)(param_2 + 0xe8) = 7;
  return;
}
