#include "types.h"

// Batch decompiled via Ghidra MCP -- pool-b, batch 006
// Range: 0x7101000000 -- 0x7101FFFFFF

// Forward declarations
[[noreturn]] extern "C" void abort();
extern "C" s32 __cxa_guard_acquire(s64 *);
extern "C" void __cxa_guard_release(s64 *);

// Data symbols -- guard vars
extern u64 DAT_71052c08d0;
extern u64 DAT_71052c0900;
// Data symbols -- vtable pointers
extern void *DAT_71052c08c8;
extern void *DAT_71052c0908;
// PTR_LAB targets
extern u8 PTR_LAB_7105026340;
extern u8 PTR_LAB_7105028988;

// ── __throw_out_of_range thunks ───────────────────────────────────────────────
// Each is a noreturn wrapper generated by different vector instantiations.

// 0x710104a7e4
[[noreturn]] void FUN_710104a7e4()
{
  abort();
}

// 0x710104a97c
[[noreturn]] void FUN_710104a97c()
{
  abort();
}

// 0x710104ab5c
[[noreturn]] void FUN_710104ab5c()
{
  abort();
}

// 0x710104acbc
[[noreturn]] void FUN_710104acbc()
{
  abort();
}

// 0x710104ad9c
[[noreturn]] void FUN_710104ad9c()
{
  abort();
}

// 0x710104af4c
[[noreturn]] void FUN_710104af4c()
{
  abort();
}

// 0x710104b00c
[[noreturn]] void FUN_710104b00c()
{
  abort();
}

// 0x710104b0cc
[[noreturn]] void FUN_710104b0cc()
{
  abort();
}

// 0x710106953c
[[noreturn]] void FUN_710106953c()
{
  abort();
}

// 0x71010695fc
[[noreturn]] void FUN_71010695fc()
{
  abort();
}

// 0x71010696bc
[[noreturn]] void FUN_71010696bc()
{
  abort();
}

// 0x710106977c
[[noreturn]] void FUN_710106977c()
{
  abort();
}

// 0x710106983c
[[noreturn]] void FUN_710106983c()
{
  abort();
}

// 0x71010698fc
[[noreturn]] void FUN_71010698fc()
{
  abort();
}

// 0x7101069aac
[[noreturn]] void FUN_7101069aac()
{
  abort();
}

// 0x7101069c8c
[[noreturn]] void FUN_7101069c8c()
{
  abort();
}

// 0x7101069dbc
[[noreturn]] void FUN_7101069dbc()
{
  abort();
}

// ── vtable call wrappers ──────────────────────────────────────────────────────

// 0x7101008dd0 -- address appears to be mid-function; removed bad decompilation

// ── Guard-init vtable setters ─────────────────────────────────────────────────

// 0x7101043990 -- original is mov x0,xzr; ret (return 0 stub)
u64 FUN_7101043990() { return 0; }

// 0x710105bc40 -- original is mov x0,xzr; ret (return 0 stub)

namespace std { namespace __1 {
template<bool> struct __vector_base_common {
    [[noreturn]] static void __throw_out_of_range();
};
}}

u64 FUN_710105bc40() { return 0; }
