#include "types.h"

// MEDIUM-tier FUN_* functions — 0x7101 range, batch d5-001
// Pool-d worker: auto-generated from Ghidra decompilation
// Includes: abort() thunks, __throw_out_of_range thunks, global-dispatch wrappers

// ---- External declarations -----------------------------------------------

[[noreturn]] extern "C" void abort();

extern "C" void FUN_71002ec1a0(u64);
extern "C" void FUN_710114d0a0(u64, u64, u32);
extern "C" void FUN_71014f7da0(u64);
extern "C" void FUN_71014f10c0(u64);
extern "C" void FUN_710150b040(u64);
extern "C" void FUN_710150f0c0(u64);
extern "C" u32  FUN_7101325d20();

extern "C" u64 *DAT_71052c2760;

// ---- abort() thunks -------------------------------------------------------
// Each is a [[noreturn]] wrapper around abort() generated by the compiler
// for various template instantiation sites.

// 0x710138cfc0
[[noreturn]] void FUN_710138cfc0(void) { abort(); }

// 0x7101390038
[[noreturn]] void FUN_7101390038(void) { abort(); }

// 0x71013ccd88
[[noreturn]] void FUN_71013ccd88(void) { abort(); }

// 0x71013cf078
[[noreturn]] void FUN_71013cf078(void) { abort(); }

// 0x710141ca78
[[noreturn]] void FUN_710141ca78(void) { abort(); }

// 0x7101533938
[[noreturn]] void FUN_7101533938(void) { abort(); }

// 0x7101590468
[[noreturn]] void FUN_7101590468(void) { abort(); }

// 0x710179e928
[[noreturn]] void FUN_710179e928(void) { abort(); }

// 0x710181e888
[[noreturn]] void FUN_710181e888(void) { abort(); }

// 0x7101886e78
[[noreturn]] void FUN_7101886e78(void) { abort(); }

// 0x7101adcd78
[[noreturn]] void FUN_7101adcd78(void) { abort(); }

// 0x7101c170e8
[[noreturn]] void FUN_7101c170e8(void) { abort(); }

// 0x7101c3ee88
[[noreturn]] void FUN_7101c3ee88(void) { abort(); }

// 0x7101cd0978
[[noreturn]] void FUN_7101cd0978(void) { abort(); }

// 0x7101ce9698
[[noreturn]] void FUN_7101ce9698(void) { abort(); }

// 0x7101d369f8
[[noreturn]] void FUN_7101d369f8(void) { abort(); }

// 0x710146cba4
[[noreturn]] void FUN_710146cba4(void) { abort(); }

// 0x7101541c54
[[noreturn]] void FUN_7101541c54(void) { abort(); }

// 0x7101542904
[[noreturn]] void FUN_7101542904(void) { abort(); }

// 0x71019dcf34
[[noreturn]] void FUN_71019dcf34(void) { abort(); }

// ---- __throw_out_of_range thunks -----------------------------------------
// Generated by libc++ vector OOB checks; all call abort in this binary.

// 0x7101b1baec
[[noreturn]] void FUN_7101b1baec(void) { abort(); }

// 0x7101e42f34
[[noreturn]] void FUN_7101e42f34(void) { abort(); }

// ---- Simple wrappers ------------------------------------------------------

// 0x710114d080 — forward to FUN_710114d0a0 with sentinel -1, return 1
u64 FUN_710114d080(u64 param_1, u64 param_2)
{
    FUN_710114d0a0(param_1, param_2, 0xffffffff);
    return 1;
}

// 0x7101325d00 — return NOT(FUN_7101325d20()) & 1
u32 FUN_7101325d00(void)
{
    u32 uVar1;
    uVar1 = FUN_7101325d20();
    return ~uVar1 & 1;
}

// 0x7101615ac0 — vtable dispatch: call slot +0xc0 on *param_1
void FUN_7101615ac0(s64 *param_1)
{
    (*(void (**)())(*param_1 + 0xc0))();
}

// 0x7101f836e0 — call FUN_71002ec1a0 with *(param_1 - 8)
u32 FUN_7101f836e0(s64 param_1)
{
    FUN_71002ec1a0(*(u64 *)(param_1 - 8));
    return 0;
}

// 0x7101342780 — dispatch to FUN_71014f7da0 with dereferenced global
void FUN_7101342780(void)
{
    FUN_71014f7da0(*DAT_71052c2760);
}

// 0x710151a190 — dispatch to FUN_710150f0c0 with dereferenced global
void FUN_710151a190(void)
{
    FUN_710150f0c0(*DAT_71052c2760);
}

// 0x710151a4c0 — dispatch to FUN_71014f10c0 with dereferenced global
void FUN_710151a4c0(void)
{
    FUN_71014f10c0(*DAT_71052c2760);
}

// 0x71014d3a30 — dispatch to FUN_710150b040 with dereferenced global
void FUN_71014d3a30(void)
{
    FUN_710150b040(*DAT_71052c2760);
}
