// Library Function Address Map — SSBU v13.0.4
// Generated by pool-a identification pass, 2026-04-08
//
// This file documents the address ranges and identities of third-party
// library code linked into the SSBU binary. These functions are compiled
// by NX Clang at various optimization levels and CANNOT be byte-matched
// against upstream source compiled with standard Clang 8.0.0.
//
// =======================================================================
// ADDRESS RANGE SUMMARY
// =======================================================================
//
// 0x7100000xxx-0x7100028xxx  curl (99 functions, already named)
// 0x710392dxxx-0x710396xxxx  jemalloc 5.1.0 (~145 functions, partially identified)
// 0x7103993580-0x710399a4e0  nus3audio / XDSP audio DSP (~25 functions)
// 0x710399d650-0x710399f0b0  LZ4 v1.8.x (5 functions identified)
// 0x710399f530-0x710399f880  XXH64 (3 functions, used by zstd v0.7)
// 0x71039a0150-0x71039a9e00  zstd modern (FSE/HUF + ZSTD_decompressBlock_internal)
// 0x71039a3ca0-0x71039af860  zstd v0.4 legacy chain + helpers
// 0x71039afb20-0x71039b6370  zstd v0.5 legacy chain + helpers
// 0x71039b86d0-0x71039bbed0  zstd v0.6 legacy chain + helpers
// 0x71039bc170-0x71039bf5f0  zstd v0.7 legacy chain + helpers
// 0x71039bfa70-0x71039c7e80  C++ runtime / PLT stubs
//
// =======================================================================
// LIBRARY VERSIONS
// =======================================================================
//
// jemalloc:  5.1.0 (Nintendo fork, compiled at -O0)
// zstd:      v1.3.7, ZSTD_LEGACY_SUPPORT=4 (v0.4-v0.7)
// LZ4:       v1.8.x (via Nintendo SDK 8.2.1)
// zlib:      1.2.11.f-NINTENDO-SDK-v1
// curl:      (version TBD, 99 named functions)
// XDSP:      Xbox DSP library (DirectXMath Audio, NX port)
// nus3audio: Bandai Namco proprietary (NUS3BANK format)
// XXH32:     bundled with LZ4
// XXH64:     bundled with zstd (v0.7 content checksums)
//
// =======================================================================
// KEY MAGIC NUMBERS
// =======================================================================
//
// 0xFD2FB524  zstd legacy v0.4 frame magic
// 0xFD2FB525  zstd legacy v0.5 frame magic
// 0xFD2FB526  zstd legacy v0.6 frame magic
// 0xFD2FB527  zstd legacy v0.7 frame magic
// 0xFD2FB528  zstd modern frame magic (v0.8+)
// 0x184D2A5x  zstd skippable frame magic (x = 0-F)
// 0x04224D18  LZ4 frame magic (LZ4F)
// 0x5355504f  "OPUS" header in NUS3BANK audio
//
// =======================================================================
// ZSTD LEGACY DECOMPRESSION CALL TREE
// =======================================================================
//
// ZSTD_decompressLegacyStream (0x71039a6cd0)
// |
// +-- case 4 (v0.4): ZSTDv04_decompressContinue (0x71039af600)
// |   +-- ZSTDv04_decompressBlock (0x71039aab60, 5544B)
// |   +-- FSE_readNCount (0x71039ac110, 692B)
// |   +-- HUF helpers...
// |
// +-- case 5 (v0.5): ZSTDv05_decompressContinue (0x71039b4fc0)
// |   +-- ZSTDv05_decompressBlock (0x71039b3370, 7248B)
// |   +-- FSE_readNCount (0x71039b5230, 692B)
// |   +-- HUF helpers...
// |
// +-- case 6 (v0.6): ZSTDv06_decompressContinue (0x71039ba300)
// |   +-- ZSTDv06_decompressBlock (0x71039b88f0, 6668B)
// |   +-- FSE_readNCount (0x71039ba620, 692B)
// |   +-- HUF helpers...
// |
// +-- case 7 (v0.7): ZSTDv07_decompressContinue (0x71039bf5f0)
//     +-- ZSTDv07_decompressBlock (0x71039bc6c0, 12072B)
//     +-- ZSTDv07_decodeFrameHeader (0x71039bc200, 120B)
//     +-- XXH64_update (0x710399f530)
//     +-- XXH64_digest (0x710399f6c0)

#ifndef LIBRARY_MAP_H
#define LIBRARY_MAP_H

// Intentionally empty — this file is documentation only.
// Individual library types are in their respective headers.

#endif // LIBRARY_MAP_H
