#!/usr/bin/env python3
"""
Generate stub source files for all undecompiled functions.

Produces minimal extern "C" function definitions so that a full link can be
attempted.  Each stub compiles to a single `ret` instruction; the linker
script (generated by gen_linker_script.py) places it at the original address.

Usage:
    python tools/gen_stubs.py          # Generate stubs in src/stubs/
    python tools/gen_stubs.py --clean  # Remove generated stubs
    python tools/gen_stubs.py --dry    # Print stats without writing
"""

import csv
import re
import shutil
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
FUNCTIONS_CSV = PROJECT_ROOT / "data" / "functions.csv"
STUBS_DIR = PROJECT_ROOT / "src" / "stubs"

# Functions per generated .cpp file — keeps compile times reasonable
CHUNK_SIZE = 5000

# Valid C identifier (extern "C" linkage, no mangling)
VALID_C_IDENT = re.compile(r'^[a-zA-Z_][a-zA-Z0-9_]*$')


def sanitize_name(name, addr):
    """Return a valid C identifier for the stub, or None to skip."""
    if VALID_C_IDENT.match(name):
        return name
    # Fall back to address-based name for destructors, operators, templates, etc.
    return "FUN_%x" % addr


def read_stubs():
    """Read functions.csv and return list of (addr, size, stub_name) for U-quality."""
    stubs = []
    # Pre-populate seen_names with compiled (M/N) function names to avoid conflicts
    seen_names = set()

    with open(FUNCTIONS_CSV) as f:
        reader = csv.reader(f)
        next(reader)  # skip header
        rows = list(reader)

    # First pass: collect compiled function names
    for row in rows:
        if row[1] in ('M', 'N'):
            seen_names.add(row[3])

    # Second pass: generate stubs for U-quality
    for row in rows:
        addr_str, quality, size_str, name = row[0], row[1], row[2], row[3]
        if quality != 'U':
            continue

        addr = int(addr_str, 16)
        size = int(size_str)
        stub_name = sanitize_name(name, addr)

        if stub_name is None:
            continue

        # Deduplicate — some names appear at multiple addresses or conflict
        # with already-compiled functions
        if stub_name in seen_names:
            stub_name = "FUN_%x" % addr
        seen_names.add(stub_name)

        stubs.append((addr, size, stub_name))

    stubs.sort()
    return stubs


def generate_chunk(stubs, chunk_idx, filename):
    """Write one chunk of stubs to a .cpp file."""
    with open(filename, 'w') as f:
        f.write("// Auto-generated stubs for undecompiled functions (chunk %d)\n"
                % chunk_idx)
        f.write("// Do not edit — regenerate with: python tools/gen_stubs.py\n")
        f.write("// These provide symbol definitions for full-link attempts.\n\n")

        for addr, size, stub_name in stubs:
            f.write("// 0x%x | size=%d\n" % (addr, size))
            f.write('extern "C" void %s() {}\n\n' % stub_name)


def main():
    if '--clean' in sys.argv:
        if STUBS_DIR.exists():
            shutil.rmtree(STUBS_DIR)
            print("Removed %s" % STUBS_DIR)
        else:
            print("Nothing to clean.")
        return

    stubs = read_stubs()
    n_chunks = (len(stubs) + CHUNK_SIZE - 1) // CHUNK_SIZE

    if '--dry' in sys.argv:
        print("Would generate %d stubs in %d files" % (len(stubs), n_chunks))
        print("  Output: %s/stubs_NNN.cpp" % STUBS_DIR)
        # Show size distribution
        sizes = [s for _, s, _ in stubs]
        print("  Size range: %d – %d bytes" % (min(sizes), max(sizes)))
        print("  Total .text coverage: %.1f MB"
              % (sum(sizes) / 1024 / 1024))
        return

    # Clean and regenerate
    if STUBS_DIR.exists():
        shutil.rmtree(STUBS_DIR)
    STUBS_DIR.mkdir(parents=True)

    for i in range(0, len(stubs), CHUNK_SIZE):
        chunk = stubs[i:i + CHUNK_SIZE]
        chunk_idx = i // CHUNK_SIZE
        filename = STUBS_DIR / ("stubs_%03d.cpp" % chunk_idx)
        generate_chunk(chunk, chunk_idx, filename)

    print("Generated %d stubs in %d files -> %s/" % (len(stubs), n_chunks, STUBS_DIR))
    print("  Run 'cmd /c build.bat' or 'python tools/build.py' to compile.")
    print("  Then 'python tools/gen_linker_script.py' to update the linker script.")


if __name__ == '__main__':
    main()
