#!/usr/bin/env python3
"""Sync WORKER-pool-{letter}.md files from all pool worktrees into data/pool_assignments.md.

Each pool's WORKER-pool-{letter}.md is the single source of truth. This script reads each
pool's worker file and generates the overview table in pool_assignments.md.

Usage: python tools/sync_assignments.py
"""
import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)
PARENT_DIR = os.path.dirname(REPO_ROOT)
POOL_NAMES = ["pool-a", "pool-b", "pool-c", "pool-d", "pool-e",
              "pool-f", "pool-g", "pool-h", "pool-i", "pool-j"]
OUTPUT = os.path.join(REPO_ROOT, "data", "pool_assignments.md")


def parse_worker_md(path):
    """Extract key fields from a WORKER.md file."""
    if not os.path.exists(path):
        return None
    with open(path, "r") as f:
        text = f.read()

    def extract(pattern, default="—"):
        m = re.search(pattern, text, re.IGNORECASE)
        return m.group(1).strip() if m else default

    model = extract(r"##\s*Model:\s*(.+)")
    task = extract(r"##\s*Task:\s*(.+)")
    territory_match = re.search(
        r"##\s*File Territory\s*\n((?:- .+\n?)+)", text, re.IGNORECASE
    )
    territory = (
        territory_match.group(1).replace("- ", "").replace("\n", ", ").strip(", ")
        if territory_match
        else "—"
    )
    progress_match = re.search(r"##\s*Progress.*?\n(.+)", text, re.IGNORECASE)
    progress = progress_match.group(1).strip() if progress_match else "—"

    # Determine status from progress text
    status = "active"
    if "complete" in progress.lower() and "100%" in progress:
        status = "exhausted"

    return {
        "model": model,
        "task": task,
        "territory": territory,
        "progress": progress[:80],
        "status": status,
    }


def main():
    rows = []
    for pool in POOL_NAMES:
        worktree = os.path.join(PARENT_DIR, f"SSBU Decomp-{pool}")
        worker_md = os.path.join(worktree, f"WORKER-{pool}.md")
        info = parse_worker_md(worker_md)
        if info:
            rows.append((pool, info))
        else:
            rows.append(
                (
                    pool,
                    {
                        "model": "—",
                        "task": f"NO WORKER-{pool}.md",
                        "territory": "—",
                        "progress": "—",
                        "status": "unassigned",
                    },
                )
            )

    with open(OUTPUT, "w") as f:
        f.write("# Pool Assignments\n\n")
        f.write(
            "**Auto-generated by `python tools/sync_assignments.py`** — do NOT edit manually.\n"
        )
        f.write("**Source of truth is each pool's `WORKER-pool-{letter}.md`.**\n\n")
        f.write("| Pool | Model | Task | File Territory | Status |\n")
        f.write("|------|-------|------|----------------|--------|\n")
        for pool, info in rows:
            f.write(
                f"| {pool} | {info['model']} | {info['task']} | {info['territory']} | {info['status']} |\n"
            )
        f.write("\n**Update WORKER-pool-{letter}.md in the pool's worktree when assigning work** — "
                "then run this script to sync.\n")

    print(f"Updated {OUTPUT}")
    for pool, info in rows:
        print(f"  {pool}: {info['task']} [{info['status']}]")


if __name__ == "__main__":
    main()
